# Use an official Ubuntu 24.04 base image
FROM ubuntu:24.04

# Disable interactive prompts during package install
# Set default timezone
# Remove timestamp noise in toybox > .config
# Set vi as the default editor
ENV \
  DEBIAN_FRONTEND=noninteractive \
  TZ=Etc/UTC \
  KCONFIG_NOTIMESTAMP=1 \
  EDITOR=vi

# Docker image metadata
LABEL \
  org.opencontainers.image.authors="Balaji Pothula - balan.pothula@gmail.com" \
  org.opencontainers.image.base.name="ubuntu:24.04" \
  org.opencontainers.image.title="toybox" \
  org.opencontainers.image.version="0.8.13" \
  org.opencontainers.image.description="Toybox: all-in-one Linux command line." \
  org.opencontainers.image.vendor="Techonomy Solutions Pvt. Ltd. - https://techonomy.in"

# Install required toybox and kernel dependencies
RUN \
  apt update && \
  apt install --yes --no-install-recommends \
    build-essential \
    git \
    bc \
    bison \
    flex \
    libelf-dev \
    libssl-dev \
    erofs-utils \
    curl \
    cpio \
    ca-certificates \
    dropbear-bin \
    wget \
    vim \
    xz-utils && \
  rm -rf /var/lib/apt/lists/*

# Clone toybox sources pinned to 0.8.13
RUN \
  git clone --branch 0.8.13 --depth 1 https://github.com/landley/toybox.git /toybox && \
  git clone --branch linux-6.12.y --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git /linux

# Copy LiteOS Network configuration
COPY lite_os.config /toybox/.config

# Copy musl-libc prebuilt cross-compiler toolchain.
COPY x86_64-linux-musl-cross /x86_64-linux-musl-cross

# Set /toybox as the working directory
WORKDIR /toybox

